# Generated by Django 6.1 on 2026-09-05 16:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/user.png', upload_to=api.models.profile_path),
        ),
    ]
