# Generated by Django 6.1.1 on 2026-09-14 16:20

import api.models
from django.db import migrations, models

# MEDIA_ROOT moved from BASE_DIR to BASE_DIR/'media', so stored paths lose the
# leading 'media/' segment they only needed under the old layout.
OLD_DEFAULT = 'media/user.png'
NEW_DEFAULT = 'user.png'


def strip_media_prefix(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.filter(avatar=OLD_DEFAULT).update(avatar=NEW_DEFAULT)


def restore_media_prefix(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.filter(avatar=NEW_DEFAULT).update(avatar=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to=api.models.profile_path),
        ),
        migrations.RunPython(strip_media_prefix, restore_media_prefix),
    ]
