# Generated by Django 6.1.1 on 2026-09-14 17:02

import api.models
from django.db import migrations, models


# The placeholder avatar is gone: rows still pointing at it are cleared so the
# SPA falls back to the user's initials instead of requesting a missing file.
PLACEHOLDER = 'user.png'


def clear_placeholder(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.filter(avatar=PLACEHOLDER).update(avatar='')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=api.models.profile_path),
        ),
        # No reverse: which profiles were blank before this ran vs. cleared
        # by it isn't recorded anywhere, so a "restore" can only guess and
        # would overwrite unrelated profiles (new signups, deliberately
        # cleared avatars) with a placeholder they never had.
        migrations.RunPython(clear_placeholder, migrations.RunPython.noop),
    ]
