# Generated by Django 6.1.1 on 2026-09-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
